TAP version 14
# [WILDCARD]failing_steps.ts
# Subtest: nested failure
    not ok 1 - inner 1
      ---
      {"message":"Error: Failed.\n      throw new Error(\"Failed.\");\n            ^\n    at [WILDCARD]/failing_steps.ts:[WILDCARD]\n[WILDCARD]","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
      ...
    ok 2 - inner 2
    not ok 3 - step 1
      ---
      {"message":"1 test step failed.","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
      ...
    1..3
not ok 1 - nested failure
  ---
  {"message":"1 test step failed.","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
  ...
# Subtest: multiple test step failures
    not ok 1 - step 1
      ---
      {"message":"Error: Fail.\n    throw new Error(\"Fail.\");\n          ^\n    at [WILDCARD]/failing_steps.ts:[WILDCARD]\n[WILDCARD]","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
      ...
    not ok 2 - step 2
      ---
      {"message":"Error: Fail.\n  await t.step(\"step 2\", () => Promise.reject(new Error(\"Fail.\")));\n                                              ^\n    at [WILDCARD]/failing_steps.ts:[WILDCARD]\n[WILDCARD]","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
      ...
    1..2
not ok 2 - multiple test step failures
  ---
  {"message":"2 test steps failed.","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
  ...
# Subtest: failing step in failing test
    not ok 1 - step 1
      ---
      {"message":"Error: Fail.\n    throw new Error(\"Fail.\");\n          ^\n    at [WILDCARD]/failing_steps.ts:[WILDCARD]\n[WILDCARD]","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
      ...
    1..1
not ok 3 - failing step in failing test
  ---
  {"message":"Error: Fail test.\n  throw new Error(\"Fail test.\");\n        ^\n    at [WILDCARD]/failing_steps.ts:[WILDCARD]","severity":"fail","at":{"file":"[WILDCARD]failing_steps.ts","line":[WILDCARD]}}
  ...
1..3
error: Test failed
